version: "3.9"

services:
  mohana:
    image: redis:7
    container_name: redis-server
    networks:
      - my-network

  client:
    image: redis:7
    container_name: redis-client
    depends_on:
      - mohana
    networks:
      - my-network
    command: ["sleep", "infinity"]

networks:
  my-network:
    driver: bridge
